#!/bin/bash

[[ DEBUG -gt 0 ]] && set -x

PROGNAME=${0##*/}
PROGNAME=${PROGNAME%.*}

usage () {
    printf "Setup Sendmail to use AWS SES SMTP server on MacOS.\n"
    printf "Use sudo to run this script as root.\n"
	printf "${PROGNAME}\n"
    printf "\t-d SES_DOMAIN\n"
    printf "\t-r REGION\n"
    printf "\t-u SMTP_USERNAME\n"
    printf "\t-p SMTP_PASSWORD\n"
    printf "\t[-t TEST_EMAIL_SEND_TO]\n"
    printf "\t[-h]\n\n"

    printf "OPTIONS\n"
    printf "\t-d SES_DOMAIN\n\n"
    printf "\tDomain setup in AWS SES.\n\n"

    printf "\t-r REGION\n\n"
    printf "\tAWS Region used by SES.\n\n"

    printf "\t-u SMTP_USERNAME\n\n"
    printf "\tUsername of AWS SES SMTP.\n\n"

    printf "\t-p SMTP_PASSWORD\n\n"
    printf "\tUsername of AWS SES SMTP.\n\n"

    printf "\t[-t TEST_EMAIL_SEND_TO]\n\n"
    printf "\tAn Email address to test this setup.\n\n"


    printf "\t[-h]\n\n"
    printf "\tThis help.\n\n"
    exit 255
}

while getopts d:r:u:p:t:h opt; do
    case $opt in
        d)
            SES_DOMAIN=$OPTARG
            ;;
        r)
            REGION=$OPTARG
            ;;
        u)
            SMTP_USERNAME=$OPTARG
            ;;
        p)
            SMTP_PASSWORD=$OPTARG
            ;;
        t)
            TEST_EMAIL_SEND_TO=$OPTARG
            ;;
        h|*)
            usage
            ;;
    esac
done

[[ -z $SES_DOMAIN || -z $REGION || -z $SMTP_USERNAME || -z $SMTP_PASSWORD ]] && usage

# Variables
mark_begin="# BEGIN == Generated by ${PROGNAME}"
mark_end="# END == Generated by ${PROGNAME}"
config="
relayhost = [email-smtp.${REGION}.amazonaws.com]:25
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_use_tls = yes
smtp_tls_security_level = encrypt
smtp_tls_note_starttls_offer = yes
smtp_sasl_mechanism_filter = plain
"

# /etc/postfix/main.cf
echo "Modifying /etc/postfix/main.cf"
inject_to_file -c "$config" -f /etc/postfix/main.cf \
               -p after \
               -a "^#relayhost = \[an.ip.add.ress\]$" \
               -m "$mark_begin" \
               -n "$mark_end" \
               -x "$mark_begin" \
               -y "$mark_end" || exit

# /etc/postfix/sasl_passwd
echo "Modifying /etc/postfix/sasl_passwd"
cat > /etc/postfix/sasl_passwd << EOF || exit
[email-smtp.${REGION}.amazonaws.com]:25 ${SMTP_USERNAME}:${SMTP_PASSWORD}
EOF

# /etc/postfix/sasl_passwd.db
echo "Generating /etc/postfix/sasl_passwd.db"
rm -f /etc/postfix/sasl_passwd.db || exit
postmap /etc/postfix/sasl_passwd || exit
chmod 0600 /etc/postfix/sasl_passwd || exit
chmod 0600 /etc/postfix/sasl_passwd.db || exit

# Restart Sendmail service
postfix stop
postfix start || exit

# Send test Email to verify the installation
if [[ -n $TEST_EMAIL_SEND_TO ]]; then
    echo "Sending test Email to $TEST_EMAIL_SEND_TO"
    sendmail -F "${PROGNAME}" -f "no-reply@$SES_DOMAIN" -t "$TEST_EMAIL_SEND_TO" << EOF
Subject: ${PROGNAME} test Email
To: $TEST_EMAIL_SEND_TO
This is a test Email sent from MacOS through AWS SES SMTP service.
EOF
fi

exit
